apiVersion: apps/v1
kind: Deployment
metadata: 
  name: goserver
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: server
  template:
    metadata:
      labels: 
        app: server
    spec: 
      containers:
        - name: goserver
          image: ladgelson/livek8s:v2
          ports: 
            - containerPort: 3000